# Добавь path_provider в блок dependencies (если его там еще нет)
dependencies:
  path_provider: ^2.1.2

# Добавь flutter_launcher_icons в блок dev_dependencies
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

# Вставь этот блок в самый конец файла
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/icon_black.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_black.png"
